# Generated by Django 5.1.7 on 2025-03-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email (Optional)')),
                ('category', models.CharField(choices=[('suggestion', 'Suggestion'), ('bug', 'Bug Report'), ('other', 'Other')], default='suggestion', max_length=20, verbose_name='Feedback Category')),
                ('message', models.TextField(verbose_name='Your Message')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted At')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback Entries',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
