# Generated by Django 5.1.7 on 2025-03-16 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_order_estimated_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='estimated_delivery_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 21, 17, 11, 49, 640221, tzinfo=datetime.timezone.utc)),
        ),
    ]
