# Generated by Django 5.1.7 on 2025-03-10 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_subscriber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscriber',
        ),
    ]
